### PR TITLE
Fix 22 and 23

### LINKED ISSUE #22: Missing null check causes exception
There is a missing null check in [unified.coffee](https://github.com/activeprospect/leadconduit-integration-lendingtree/blob/6b8da5002360d3966ed8d4d1f0b0d0a45ed2ced9/src/unified.coffee#L23). This caused [an error in production](https://app.honeybadger.io/projects/2160/faults/10831882#notice-summary).

### PR DESCRIPTION
**Pull request by zalary**
fix #22 (missing null check causes exception) and #23 (parse loan reason fails when there are multiple reasons)

### CODE REVIEW

File: src/parse.coffee [hunk 1]
```diff
@@ -58,19 +58,30 @@ parseLoanPurpose = (value) ->
...
-    when 'homebuying' then 'home buying'
-    when 'carfinancing' then 'car finance'
-    when 'payoffheloan' then 'pay off home equity loan'
-    when 'payoffheloc' then 'pay off home equity line of credit'
-    when 'greenloan' then 'green loan'
-    else value
+  return null unless value?
+  result = []
+  if typeof value is 'string'
+    array = []
```
Comment (cgrayson) [inline src/parse.coffee]: Maybe a more descriptive name? :-) Something like `reasons`?

File: src/parse.coffee [hunk 2]
```diff
@@ -58,19 +58,30 @@ parseLoanPurpose = (value) ->
     else null
 
 parseLoanReason = (value) ->
```
Comment (cgrayson) [inline src/parse.coffee]: Might make this plural "Reasons", now.

**Comment by cgrayson** [comment]
Otherwise LGTM
